# Generated by Django 5.2 on 2025-05-04 06:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
                ('facebook', models.TextField(blank=True)),
                ('twitter', models.TextField(blank=True)),
                ('instagram', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('product_details', ckeditor.fields.RichTextField(blank=True)),
                ('review', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
