# Generated by Django 5.2 on 2025-04-28 06:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('footer', ckeditor.fields.RichTextField(blank=True)),
                ('delivery', ckeditor.fields.RichTextField(blank=True)),
                ('payment', ckeditor.fields.RichTextField(blank=True)),
                ('confidence', ckeditor.fields.RichTextField(blank=True)),
                ('help', ckeditor.fields.RichTextField(blank=True)),
                ('twitter', models.TextField(blank=True)),
                ('facebook', models.TextField(blank=True)),
                ('youtube', models.TextField(blank=True)),
                ('instagram', models.TextField(blank=True)),
            ],
        ),
    ]
